name: Hello world docker
description: greet someone
author: raresf

# Define your inputs here.
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World

# Define your outputs here.
outputs:
  time:
    description: The time we said hello

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
